import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { basename, join, relative } from 'node:path'
import { listRuleSourcePaths, rulesSourceDir } from '@/gov/install'
import { parseFrontmatter } from '@/indexes/frontmatter'

const STANDARDS_REL = 'standards'

/** The band the generated rules ship in, named for what they point at. */
export const STANDARD_RULES_BAND = 'standards'

export type StandardRulesResult =
  | { readonly ok: true; readonly written: readonly string[] }
  | { readonly ok: false; readonly reason: string }

interface StandardRule {
  readonly name: string
  readonly sourceRel: string
  readonly title: string
  readonly description: string
  readonly paths: readonly string[]
  readonly bullets: readonly string[]
}

export function standardRulesDir(root: string): string {
  return join(rulesSourceDir(root), STANDARD_RULES_BAND)
}

/**
 * Generates one path-scoped rule per standard whose frontmatter carries
 * `paths:`. The standard owns the glob and the operative bullets, so the rule
 * is output, committed beside the authored bands so every reader of
 * `governance/rules/` sees it as an ordinary file.
 *
 * Every standard is read and checked before anything is written, so a refusal
 * leaves the previous output whole rather than half cleared.
 */
export async function regenStandardRules(
  root: string,
): Promise<StandardRulesResult> {
  const standardsDir = join(root, STANDARDS_REL)
  if (!existsSync(standardsDir)) return { ok: true, written: [] }

  const reserved = reservedNames(root)
  const rules: StandardRule[] = []

  for (const file of readdirSync(standardsDir).sort()) {
    if (!file.endsWith('.md')) continue
    const read = readStandard(root, file, reserved)
    if (typeof read === 'string') return { ok: false, reason: read }
    if (read !== undefined) rules.push(read)
  }

  const dir = standardRulesDir(root)
  await rm(dir, { recursive: true, force: true })
  if (rules.length > 0) await mkdir(dir, { recursive: true })

  const written: string[] = []
  for (const rule of rules) {
    const dest = join(dir, `${rule.name}.md`)
    await writeFile(dest, renderStandardRule(rule))
    written.push(relative(root, dest))
  }

  return { ok: true, written }
}

/**
 * Band folders and authored rule basenames. A bare-word rule name equal to a
 * band would install the whole band through `--add`, and one equal to an
 * authored rule would shadow it in the name index.
 */
function reservedNames(root: string): {
  readonly bands: ReadonlySet<string>
  readonly rules: ReadonlySet<string>
} {
  const bands = new Set<string>([STANDARD_RULES_BAND])
  const rules = new Set<string>()

  for (const rel of listRuleSourcePaths(root)) {
    const segments = rel.split('/')
    if (segments.length > 1) bands.add(segments[0])
    if (segments[0] === STANDARD_RULES_BAND) continue
    rules.add(basename(rel, '.md'))
  }

  return { bands, rules }
}

/** A rule to render, `undefined` for a standard with no `paths:`, or a reason. */
function readStandard(
  root: string,
  file: string,
  reserved: ReturnType<typeof reservedNames>,
): StandardRule | string | undefined {
  const sourceRel = `${STANDARDS_REL}/${file}`
  const fields = parseFrontmatter(
    readFileSync(join(root, STANDARDS_REL, file), 'utf8'),
  )?.fields
  if (fields === undefined || fields.paths === undefined) return undefined

  const name = basename(file, '.md')
  if (!isStringList(fields.paths)) {
    return `${sourceRel}: paths must be a list of strings`
  }
  if (fields.rule !== undefined && !isStringList(fields.rule)) {
    return `${sourceRel}: rule must be a list of strings`
  }
  if (reserved.bands.has(name)) {
    return `${sourceRel}: name collides with a rule band folder`
  }
  if (reserved.rules.has(name)) {
    return `${sourceRel}: name collides with an authored rule`
  }

  return {
    name,
    sourceRel,
    title: typeof fields.title === 'string' ? fields.title : name,
    description:
      typeof fields.description === 'string' ? fields.description : '',
    paths: fields.paths,
    bullets: fields.rule ?? [],
  }
}

function isStringList(value: unknown): value is string[] {
  return (
    Array.isArray(value) && value.every((entry) => typeof entry === 'string')
  )
}

function renderStandardRule(rule: StandardRule): string {
  const scope = rule.description.replace(/\.$/, '')
  const pointer = [
    `Follow the ${rule.name} standard for ${lowerFirst(scope)}.`,
    'It is the single source.',
    `Read it with \`canon standards ${rule.name}\`.`,
  ].join(' ')

  return [
    '---',
    `# Generated by \`canon gov regen\` from ${rule.sourceRel}. Edit that frontmatter, not this file.`,
    `description: ${yamlScalar(rule.description)}`,
    'paths:',
    ...rule.paths.map((glob) => `  - ${yamlQuoted(glob)}`),
    '---',
    '',
    `# ${rule.title.replace(/\breference$/, 'standards')}`,
    '',
    '## Authority',
    '',
    ...[pointer, ...rule.bullets].map((bullet) => `- ${bullet}`),
    '',
  ].join('\n')
}

function lowerFirst(text: string): string {
  return text.charAt(0).toLowerCase() + text.slice(1)
}

/** Plain when YAML would read it back unchanged, single-quoted otherwise. */
function yamlScalar(text: string): string {
  const isPlain =
    text !== '' &&
    !/^[-?:,[\]{}#&*!|>'"%@`\s]/.test(text) &&
    !/: |\s#|:$|\s$/.test(text)
  return isPlain ? text : yamlQuoted(text)
}

/**
 * Quoted the way Prettier's `singleQuote` leaves YAML, so the drift check
 * never fights the formatter: single quotes unless the text holds one and
 * double quotes would need no escape.
 */
function yamlQuoted(text: string): string {
  if (text.includes("'") && !/["\\]/.test(text)) return `"${text}"`
  return `'${text.replaceAll("'", "''")}'`
}
