import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { regenStandardRules, standardRulesDir } from '@/gov/standard-rules'

let root: string

function write(relPath: string, body: string): void {
  const path = join(root, relPath)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, body)
}

function generated(name: string): string {
  return join(standardRulesDir(root), `${name}.md`)
}

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'canon-gov-standard-rules-'))
})

afterEach(() => {
  rmSync(root, { recursive: true, force: true })
})

describe('regenStandardRules', () => {
  it('should render a rule from a standard carrying paths and rule bullets', async () => {
    write(
      'standards/plan.md',
      [
        '---',
        'title: Plan reference',
        'description: Filename and slug, required sections, and the lifecycle',
        'paths:',
        "  - '.canon/plans/**'",
        'rule:',
        "  - 'Never fill an `- Answer:` slot on behalf of its owner.'",
        '  - Move a shipped plan to the archive.',
        '---',
        '',
        '# Plan reference',
        '',
      ].join('\n'),
    )

    const result = await regenStandardRules(root)

    expect(result).toEqual({
      ok: true,
      written: ['governance/rules/standards/plan.md'],
    })
    expect(readFileSync(generated('plan'), 'utf8')).toBe(
      [
        '---',
        '# Generated by `canon gov regen` from standards/plan.md. Edit that frontmatter, not this file.',
        'description: Filename and slug, required sections, and the lifecycle',
        'paths:',
        "  - '.canon/plans/**'",
        '---',
        '',
        '# Plan standards',
        '',
        '## Authority',
        '',
        '- Follow the plan standard for filename and slug, required sections, and the lifecycle. It is the single source. Read it with `canon standards plan`.',
        '- Never fill an `- Answer:` slot on behalf of its owner.',
        '- Move a shipped plan to the archive.',
        '',
      ].join('\n'),
    )
  })

  it('should quote a description YAML would misread as plain', async () => {
    write(
      'standards/rule.md',
      [
        '---',
        'title: Rule reference',
        "description: 'Shape: the body and voice'",
        'paths:',
        "  - '**/*.md'",
        '---',
        '',
      ].join('\n'),
    )

    await regenStandardRules(root)

    expect(readFileSync(generated('rule'), 'utf8')).toContain(
      "\ndescription: 'Shape: the body and voice'\n",
    )
  })

  it('should render nothing for a standard without paths', async () => {
    write(
      'standards/slug.md',
      '---\ntitle: Slug reference\ndescription: The slug transform\n---\n',
    )

    const result = await regenStandardRules(root)

    expect(result).toEqual({ ok: true, written: [] })
    expect(existsSync(generated('slug'))).toBe(false)
  })

  it('should remove a generated rule whose standard dropped its paths', async () => {
    write('governance/rules/standards/old.md', 'stale\n')
    write(
      'standards/old.md',
      '---\ntitle: Old reference\ndescription: Nothing now\n---\n',
    )

    await regenStandardRules(root)

    expect(existsSync(generated('old'))).toBe(false)
  })

  it('should write nothing and succeed against a root with no standards folder', async () => {
    const result = await regenStandardRules(root)

    expect(result).toEqual({ ok: true, written: [] })
  })

  it('should refuse a standard named like a band folder', async () => {
    write('governance/rules/writing/markdown.md', 'prose\n')
    write(
      'standards/writing.md',
      "---\ntitle: Writing reference\ndescription: Prose\npaths:\n  - '**/*.md'\n---\n",
    )

    const result = await regenStandardRules(root)

    expect(result).toEqual({
      ok: false,
      reason: 'standards/writing.md: name collides with a rule band folder',
    })
  })

  it('should refuse a standard named like an authored rule', async () => {
    write('governance/rules/writing/prose.md', 'prose\n')
    write(
      'standards/prose.md',
      "---\ntitle: Prose reference\ndescription: Prose\npaths:\n  - '**/*.md'\n---\n",
    )

    const result = await regenStandardRules(root)

    expect(result).toEqual({
      ok: false,
      reason: 'standards/prose.md: name collides with an authored rule',
    })
  })

  it('should refuse a paths field that is not a list of strings', async () => {
    write(
      'standards/plan.md',
      "---\ntitle: Plan reference\ndescription: Plans\npaths: '.canon/plans/**'\n---\n",
    )

    const result = await regenStandardRules(root)

    expect(result).toEqual({
      ok: false,
      reason: 'standards/plan.md: paths must be a list of strings',
    })
  })

  it('should refuse a rule field that is not a list of strings', async () => {
    write(
      'standards/plan.md',
      "---\ntitle: Plan reference\ndescription: Plans\npaths:\n  - '.canon/plans/**'\nrule:\n  - 3\n---\n",
    )

    const result = await regenStandardRules(root)

    expect(result).toEqual({
      ok: false,
      reason: 'standards/plan.md: rule must be a list of strings',
    })
  })

  it('should leave the previous output in place when it refuses', async () => {
    write('governance/rules/standards/plan.md', 'kept\n')
    write(
      'standards/plan.md',
      '---\ntitle: Plan reference\ndescription: Plans\npaths: 3\n---\n',
    )

    await regenStandardRules(root)

    expect(readFileSync(generated('plan'), 'utf8')).toBe('kept\n')
  })
})
