import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { buildDesignCss } from '@/design/css'
import { renderDesignDocument } from '@/design/document'

/**
 * The two artifacts the token source produces, written by `canon design regen`
 * and asserted for drift by the `design` stage of `bun run check`.
 *
 * The document is what a person reads and the stylesheet is what a target
 * installs, and neither is edited by hand. That is the cost the operator took
 * on when the tokens moved into a module: two artifacts where the record used
 * to be one, and a regen step that has to run or both go stale silently. The
 * gate stage is what keeps silently out of it.
 */

/** The rendered record, at the path `standards/design.md` fixes for it. */
export const DESIGN_DOCUMENT = join('canon', 'DESIGN.md')

/**
 * The base stylesheet a target installs. It sits inside `src/` because that is
 * the folder the published package ships, and beside the module that writes it
 * because a generated file kept away from its generator is one nobody thinks to
 * regenerate.
 */
export const DESIGN_BASE_CSS = join('src', 'design', 'base.css')

const BASE_BANNER = [
  'Generated by `canon design regen` from src/design/tokens.ts. Do not edit.',
  'This is the base half of a design install. A target overrides a value in',
  '.claude/design/project/, which the three-way merge leaves alone, so this',
  'file changes freely and nothing a project wrote lives in it.',
].join('\n   ')

export interface RegenResult {
  readonly documentPath: string
  readonly cssPath: string
}

function write(root: string, rel: string, body: string): string {
  const path = join(root, rel)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, body)
  return path
}

export function regenDesign(root: string): RegenResult {
  return {
    documentPath: write(root, DESIGN_DOCUMENT, renderDesignDocument()),
    cssPath: write(
      root,
      DESIGN_BASE_CSS,
      buildDesignCss(undefined, { banner: BASE_BANNER }),
    ),
  }
}
